# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_posts', '0002_savedtext_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtext',
            name='lang',
            field=models.CharField(default='english', max_length=8),
        ),
    ]
